### ISSUE TITLE
Build falls after upgrading webpack to v4

### ISSUE THREAD

**Issue by dohyeondk** [DustinJackson/html-webpack-inline-source-plugin#37]
The usage of the plugin is regular. I will provide more info if needed.

```
ERROR in   TypeError: callback is not a function
  
  - index.js:27 
    [Auth0-Config]/[html-webpack-inline-source-plugin]/index.js:27:7
  
  
  - new Promise
  
  
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [Auth0-Config]/[tapable]/lib/Hook.js:35:21
  
  - index.js:679 
    [Auth0-Config]/[html-webpack-plugin]/index.js:679:45
  
  - index.js:170 
    [Auth0-Config]/[html-webpack-plugin]/index.js:170:16
  
  - util.js:16 tryCatcher
    [Auth0-Config]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [Auth0-Config]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [Auth0-Config]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [Auth0-Config]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [Auth0-Config]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [Auth0-Config]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [Auth0-Config]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [Auth0-Config]/[bluebird]/js/release/async.js:17:14
  


ERROR in   TypeError: callback is not a function
  
  - index.js:27 
    [Auth0-Config]/[html-webpack-inline-source-plugin]/index.js:27:7
  
  
  - new Promise
  
  
  - index.js:679 
    [Auth0-Config]/[html-webpack-plugin]/index.js:679:45
  
  - index.js:170 
    [Auth0-Config]/[html-webpack-plugin]/index.js:170:16
  
  - util.js:16 tryCatcher
    [Auth0-Config]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [Auth0-Config]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [Auth0-Config]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [Auth0-Config]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [Auth0-Config]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [Auth0-Config]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [Auth0-Config]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [Auth0-Config]/[bluebird]/js/release/async.js:17:14
```

**Comment by mlegenhausen** [comment]
I got another error after updating to v4

```
xxx/node_modules/tapable/lib/Tapable.js:63
		throw new Error(`Plugin could not be registered at '${name}'. Hook was not found.\n` +
        ^
Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (xxx/node_modules/tapable/lib/Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:53:15)
    at xxx/node_modules/html-webpack-inline-source-plugin/index.js:17:17
    at SyncHook.eval (eval at create (xxx/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (xxx/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (xxx/node_modules/webpack/lib/Compiler.js:418:26)
    at hooks.beforeCompile.callAsync.err (xxx/node_modules/webpack/lib/Compiler.js:457:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (xxx/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (xxx/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (xxx/node_modules/webpack/lib/Compiler.js:452:28)
    at compiler.hooks.watchRun.callAsync.err (xxx/node_modules/webpack/lib/Watching.js:77:18)
    at _err0 (eval at create (xxx/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at invalid (xxx/node_modules/webpack-dev-middleware/lib/context.js:76:7)
    at context.compiler.plugin (xxx/node_modules/webpack-dev-middleware/lib/context.js:116:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (xxx/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (xxx/node_modules/tapable/lib/Hook.js:35:21)
```

**Comment by mlegenhausen** [comment]
I fixed the plugin in #38.

**Comment by tailgo** [comment]
please update to new version~
